# Generated by Django 4.2.2 on 2023-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
