# Generated by Django 4.2.2 on 2023-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problem_difficulty_submission_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java')], max_length=10),
        ),
    ]
