# Generated by Django 4.2.2 on 2023-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_submission_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='run_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_stderr',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_stdout',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Wrong Answer', max_length=100),
        ),
    ]
