# Generated by Django 4.2.2 on 2023-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_alter_submission_options_submission_run_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2, help_text='in seconds'),
        ),
    ]
