# Generated by Django 4.2.2 on 2023-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True),
        ),
    ]
