# Generated by Django 4.2.2 on 2023-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_rename_total_questions_userprofile_total_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
