# Generated by Django 4.2.2 on 2023-07-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge.problem'),
        ),
    ]
